### ISSUE TITLE
Problem: Application home: where is website pointing

### ISSUE THREAD

**Issue by smalusa** [CulverLab/sparcd#59]
The current website is where app users access the application. wildcatresearch.arizona.edu
Currently it is unknown if the  where the website is pulling the application from - the site needs to be corrected to pull the app from latest published version on github.

**Comment by smalusa** [comment]
App should be bundled with proper link to compatible java 15 (NOT 16) for user to access if the user does not have java.

**Comment by julianpistorius** [comment]
Notes:

https://www.codejava.net/java-se/download-and-install-openjdk-15

https://download.java.net/java/GA/jdk15.0.2/0d1cfde4252546c6931946de8db48ee2/7/GPL/openjdk-15.0.2_windows-x64_bin.zip

**Comment by julianpistorius** [comment]
The website always points at the latest release build:

https://github.com/CulverLab/sparcd/releases/tag/latest

I created a wiki page with instructions on updating the release build: https://github.com/CulverLab/sparcd/wiki/Release-build

@smalusa please test the download from the website to ensure it works on Windows and macOS.

**Comment by julianpistorius** [comment]
This now works, and the instructions above will ensure it keeps working. It still involves manual steps, but we can automate it later.
