### ISSUE TITLE
Problem: Interval option not available on Analysis/Query

### ISSUE THREAD

**Issue by smalusa** [CulverLab/sparcd#63]
SPARCd 1.0 had an interval option to query for time intervals. In this science, it is convention to provide an interval time so species are not double counted on queries. This option has disappeared on 2.0 and is inoperable on SPARCd 1.0.

**Comment by Chris-Schnaufer** [comment]
@smalusa It's not clear if this is one issue or two:
- is there missing functionality regarding interval time?
- are species getting double counted queries?

Thanks

**Comment by smalusa** [comment]
Functionality on the Analyze/Query Tab of the application previously included an option to add interval (so the when queried the data would only have return in the set amount of time - this eliminates species that sit in front of a camera which creates a misrepresentation of # of individuals) The current app does not have the feature.

**Comment by Chris-Schnaufer** [comment]
This is available
