### ISSUE TITLE
Problem: Login prompt has CyVerse label - this is outdated and confusing to user

### ISSUE THREAD

**Issue by smalusa** [CulverLab/sparcd#68]
Current App Login "splash" page continues to have a "CyVerse" label as previous version. 

Label should read **SPARCd 2.0**
Change additional credit branding to include:

1.  SNRE IT, SPARCd server
2. Wild Cat Center or SPARCd server

**ADD**
1. LaBauer Lab icon

**_Shrink all credit icons_**

In current state, confusing to user

**Comment by dlebauer** [comment]
Here is our group logo: https://datascience.cals.arizona.edu/sites/datascience.cals.arizona.edu/files/CCT%20logo-primary%402x.png

Should also update README to reflect current developers and support (e.g. add Chris and Julian)

**Comment by Chris-Schnaufer** [comment]
> Here is our group logo: https://datascience.cals.arizona.edu/sites/datascience.cals.arizona.edu/files/CCT%20logo-primary%402x.png
> 
> Should also update README to reflect current developers and support (e.g. add Chris and Julian)

Issue #75 has been created for updating the README

**Comment by smalusa** [comment]
Thank you for providing the Data science logo....It will replace the logo with the login. Per the READ ME: I planned on doing it myself ----and then i discovered it is seperate files (for the latest windows and ios versions) so....not sure now....I have it written and it is as follows......PLEASE FEEL FREE TO EDIT - not sure of exact protocol.....time, rank, etc.....(those are supposed to be links....not the way it is displayed....I will add link to doc written appropriately...(https://docs.google.com/document/d/1GHLnTMFOZ0K3ur40v2_a43SS0yX28LhFPH4RZRN-mgM/edit?usp=sharing)
`SPARCd 2.0 (redesigned from [SPARCd 1.0](https://github.com/CulverLab/sparcd/tree/master/Version%20History))
•	[Dr. Melanie Culver](https://culverlab.com/dr-melanieculver/) - Principal Investigator 
•	Susan Malusa - Conceptualization, project administration, and software
•	[Dr. David LeBauer](https://datascience.cals.arizona.edu/person/david-lebauer) - Data Science and Design collaborator
•	[Chris Schnaufer ](https://datascience.cals.arizona.edu/person/christophe-schnaufer) - Software and Conceptualization SPARCd 2.0 
•	[Julian Pistorius](https://datascience.cals.arizona.edu/person/julian-pistorius) - Software and Conceptualization SPARCd 2.0`

**Comment by Chris-Schnaufer** [comment]
This change needs to be confirmed

**Comment by Chris-Schnaufer** [comment]
This change has been completed
