### ISSUE TITLE
Problem: Cannot login to SPARCd - Error 

### ISSUE THREAD

**Issue by smalusa** [CulverLab/sparcd#69]
**Describe the bug**
user receives (https://cyverse.slack.com/files/UBHPP7CR0/F03NDS3L1RN/image.pngrl) 
"Invalid username, password or url"

**To Reproduce**
Logon to SPARCd

4. See error in image above

**Expected behavior**

Add links to discussion on Slack if applicable.
https://cyverse.slack.com/archives/DDSBSE19T/p1656524614650439

**Comment by julianpistorius** [comment]
@smalusa is this still an issue or did rebooting the server fix it?

**Comment by smalusa** [comment]
Fixed.

Sent from my iPhone

On Jul 1, 2022, at 9:34 PM, Julian Pistorius ***@***.***> wrote:

﻿

External Email

@smalusa<https://github.com/smalusa> is this still an issue or did rebooting the server fix it?

**Comment by Chris-Schnaufer** [comment]
@smalusa @julianpistorius Can we close this issue?

**Comment by smalusa** [comment]
Yes, thank you.
-s

From: Chris Schnaufer ***@***.***>
Sent: Tuesday, October 11, 2022 1:20 PM
To: CulverLab/sparcd ***@***.***>
Cc: Malusa, Susan M - (smalusa) ***@***.***>; Mention ***@***.***>
Subject: [EXT]Re: [CulverLab/sparcd] Problem: Cannot login to SPARCd - Error (Issue #69)


External Email

@smalusa<https://github.com/smalusa> @julianpistorius<https://github.com/julianpistorius> Can we close this issue?
