### ISSUE TITLE
Additional service accounts

### ISSUE THREAD

**Issue by smalusa** [CulverLab/sparcd#91]
There is a need for additional service accounts. 

currently there are several url's to segregate data and appliction, for example https://wildcats.sparcd.arizona.edu; https://usfs.sparcd.arizona.edu; nps, and sandbox.....

When this seperation of accounts was initiated, I failed to include some users who are currently needing independent access and there is a need for an extra account. 

The following are the requested new services: 

- blm.sparcd.arizona.edu
- usfws.sparcd.arizona.edu
- usfstongass.sparcd.arizona.edu
i thought a service called "research01.sparcd.arizona.edu" was a good idea, but if you want to stick witht the current naming convention we can skip for now. The only reason for doing it was because I just didn't want to have to bug you if someone wants a service/url. 

 We will not have to repeat (I think) after we become a webapp - hopefully....

**Comment by julianpistorius** [comment]
Done! The service for blm already existed, and I created the other two. You should be able to log in now.

Please confirm and close this ticket once you've tested

**Comment by smalusa** [comment]
Thank you Julian!!!!
